version: '3'
services:
  frontend:
    build:
      context: ./public
      dockerfile: Dockerfile
    ports:
      - "8082:80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    volumes:
      - db-data:/usr/src/app

volumes:
  db-data:
